using UnityEngine;
using TMPro;
using UnityEngine.UI;
using UnityEngine.InputSystem;

public class Prologue : MonoBehaviour
{
    public DialogueManager dialogueManager;
    public DialogueLine[] dialogueLines;

    void Start()
    {
        dialogueLines = new DialogueLine[]
        {
        new DialogueLine("Yeonhee", "Hi, I’m Lim Yeonhee."),
        new DialogueLine("Yeonhee", "Your average student at Joesei Secondary school."),
        new DialogueLine("Yeonhee", "I’m in my third year of high school, which has been a bit hectic but fun."),
        new DialogueLine("Yeonhee", "My study stream is Humanities, which my parents hated. They wanted me to become something “reputable”, but I don’t really care about people’s opinions that much."),
        new DialogueLine("Yeonhee", "I’m what you call a die hard kpop fan, but don’t worry I'm not a Sasaeng. I just really love K-pop."),
        new DialogueLine("Yeonhee", "I love the glitz and glamour around it, and I love watching Idols live their day to day lives."),
        new DialogueLine("Yeonhee", "Sometimes it makes me wonder what my life would look like if I were a K-pop idol. If I had the opportunity to become one, I’d immediately take it. No questions asked."),
        new DialogueLine("Yeonhee", "I just didn’t expect that chance would come so soon"),
        new DialogueLine("Yeonhee", "...anyways."),
        new DialogueLine("Yeonhee", "I think their life is so much cooler compared to mine."),
        new DialogueLine("Yeonhee", "It's not like I don't have any talent either, so I'd fit into the idol world pretty well"),
        new DialogueLine("Yeonhee", "...and maybe I'll finally get to talk to my lovely Joon."),
        new DialogueLine("Yeonhee", "Sigh..."),
        new DialogueLine("Yeonhee", "My routine is the same everyday. I get there early, meet up with my friends, and we sit together scrolling through posts from the night before."),
                
        // IN CLASS
        new DialogueLine("Yuna", "Did you see the post about Starlight’s new girl group?"),
        new DialogueLine("Ji-a", "Oh my God yes."),
        new DialogueLine("Yuna", "They look so young, I was actually confused."),
        new DialogueLine("Yuna", "Apparently oldest one in the group is thirteen."),
        new DialogueLine("Yeonhee", "I saw that too...but their concept looks really cool."),
        new DialogueLine("Yuna", "That doesn’t change the fact that they’re probably getting exploited."),
        new DialogueLine("", "I shrug a little."),
        new DialogueLine("Yeonhee", "I guess..."),
        new DialogueLine("", "Then I turn my phone toward them, already smiling."),
        new DialogueLine("Yeonhee", "Anyways, did you see Joon's post? Oh my gosh, he looks so good."),
        new DialogueLine("", "Yuna sideeyes Yeonhee while Ji-a giggles beside her."),
        new DialogueLine("Ji-a", "His post was kind of hot. I won't lie."),
        new DialogueLine("Yeonhee","I know, right? I grin, leaning back in my chair. I’m actually so excited for their new vampire concept."),
        new DialogueLine("", "I sigh dramatically."),
        new DialogueLine("Yeonhee", "I seriously can’t wait to debut. Joon and I definitely have Kemi."),
        new DialogueLine("", "Yuna rolls her eyes."),
        new DialogueLine("Yuna", "Delusional. Anyways, sir’s coming."),

        //Teacher enters
        new DialogueLine("", "The teacher walks into the classroom."),
        new DialogueLine("Teacher", "Everyone back to your seats. I only want to see Art History books on the table. No maths, no English, or anything related to another subject."),
        new DialogueLine("", "The class sighs loudly."),
        new DialogueLine("", "We move slowly, dragging chairs and bags across the floor."),
        new DialogueLine("", "Yeonhee mutters under her breath."),
        new DialogueLine("Yeonhee", "I swear it’s always something."),
        new DialogueLine("", "A painting appears on the screen."),
        new DialogueLine("Teacher", "The painting of the day is The Painter’s Studio:A Real Allegory Summing Up Seven Years of My Life as an Artist by Gustave Courbet, dated 1855."),
        new DialogueLine("Teacher", "Lim Yeonhee"),
        new DialogueLine("", "The teacher scans the room and stops when Friend 1 raises their hand."),
        new DialogueLine("Teacher", "Yes?"),
        new DialogueLine("Friend 1", "Because people hate seeing the truth."),
        new DialogueLine("", "Teacher nods."),
        new DialogueLine("Teacher", "Correct.People are often blinded by power once they get a taste of it."),
        new DialogueLine("", "He gestures toward the painting."),
        new DialogueLine("Teacher", "The left side represents the exploited, and the right side shows the exploiters. The artist stands in the middle, observing both sides."),
        new DialogueLine("", "Yeonhee glances at the painting for a moment before looking back down at her laptop."),
        new DialogueLine("", "She scrolls through Instagram posts about Starlight's new girl group instead."),
        new DialogueLine("", "Minutes pass."),
        new DialogueLine("Teacher", "I want all of you to go home and sit with this painting.Think about what it means to you personally. We’ll discuss it in the next class."),
        
        new DialogueLine("", "The bell rings a few minutes later."),
        new DialogueLine("", "Yeonhee stretches."),
        new DialogueLine("Yeonhee", "Heol, that session took forever to end."),
        new DialogueLine("Friend 1", "He just wouldn’t stop talking."),
        new DialogueLine("Friend 2", "The fact that we even have to write an exam on this... you’re definitely going to fail, Yoenh.You didn’t even pay attention today."),
        new DialogueLine("", "Yeonhee shrugs."),
        new DialogueLine("Yeonhee", "It’s fine. I heard everything he said.Besides, I don’t think..."),
        new DialogueLine("Teacher", "Okay class."),
        new DialogueLine("", "The teacher interrupts."),
        new DialogueLine("Teacher", "I’m giving you this half period to study for your next assignment.No chatting."),
        new DialogueLine("", "His eyes narrow and land directly on Yeonhee."),
        new DialogueLine("", "The class giggles."),

        new DialogueLine("", "I turn to my friends immediately, pushing my laptop toward them."),
        new DialogueLine("Yeonhee", "Look at this."),
        new DialogueLine("", "They lean in."),
        new DialogueLine("Friend 1", "What are you doing? It’s our study period."),
        new DialogueLine("", "Friend 2 laughs."),
        new DialogueLine("Friend 2", "She’s probably looking at K-pop idols again."),
        new DialogueLine("", "They look at her screen."),
        new DialogueLine("Friend 2", "Called it."),
        new DialogueLine("", "Before Yeonhee can respond, a pop-up advertisement appears."),
        new DialogueLine("", "FIND YOUR DREAM AT DIAMON ENT! GLOBAL AUDITIONS OPEN NOW. LOOKING FOR THE NEXT MEMBER OF A 4-MEMBER GIRL GROUP"),
        new DialogueLine("", "All three of them stare at the screen."),

        new DialogueLine("Ji-a", "Is this real?"),
        new DialogueLine("Yuna", "It has to be fake."),
        new DialogueLine("Yeonhee", "This is destiny. (I whisper) "),
        new DialogueLine("Yuna", "No, it’s not. Don’t do something dumb."),
        new DialogueLine("Ji-a", "Yeah, t’s probably a scam."),
        new DialogueLine("", "I shake my head, eyes glued to the screen."),
        new DialogueLine("Yeonhee", "It’s literally just an advert. Look, there’s an address and everything. It’s a real company."),
        new DialogueLine("", "I can feel the excitement building in my chest."),
        new DialogueLine("Yeonhee", "I’m going to audition this Saturday."),
        new DialogueLine("Ji-a", "I don't know, Yeonhee..."),
        new DialogueLine("", "They exchange worried looks."),
        new DialogueLine("Yuna", "We really don’t think you should."),
        new DialogueLine("Teacher", "GIRLS!"),
        new DialogueLine("", "We all jump."),
        new DialogueLine("", "The teacher slams his pen against the desk."),
        new DialogueLine("Teacher", "Do I have to separate you again?"),
        new DialogueLine("", "Yeonhee sits up immediately."),
        new DialogueLine("Yeonhee", "Sorry sir. I was just showing them something for the essay."),
        new DialogueLine("", "He sighs, shaking his head."),
        new DialogueLine("Teacher", "Yeonhee, if you spent half as much time studying as you do staring at K-pop idols, you might actually rank first in this class."),
        new DialogueLine("", "I sit up straighter, closing my laptop."),
        new DialogueLine("Teacher", "This is your last warning."),
        new DialogueLine("", "After that day, everything in my life began to change… and I didn’t even notice at first."),
        new DialogueLine("", "Dad notices."),

        //Two mornings later, I’m standing in front of the company
        new DialogueLine("", "My stomach drops as I take it in."),
        new DialogueLine("", "It’s… smaller than I expected."),
        new DialogueLine("", "The paint is peeling for a new company and the building feels strangely quiet, like no one’s really there."),
        new DialogueLine("", "For a second, something about it feels off."),
        new DialogueLine("", "But I ignore it."),
        new DialogueLine("", "I step out of the car and walk toward the entrance, my heart pounding with excitement."),
        new DialogueLine("", "Inside, it's even quieter."),
        new DialogueLine("", "A recruiter sits at the front desk and looks up as I approach."),
        new DialogueLine("Recruiter", "You must be Lim Yeonhee."),
        new DialogueLine("", "I bow quickly."),
        new DialogueLine("Yeonhee", "Yes."),
        new DialogueLine("", "The recruiter smiles politely."),
        new DialogueLine("Recruiter", "Come with me. I’ll take you to the boardroom."),
        new DialogueLine("", "As we walk down the hallway, I notice how empty everything looks."),
        new DialogueLine("", "The building looked unusually empty."),
        new DialogueLine("", "Why am I the only one auditioning today? she wonders."),
        new DialogueLine("", "The recruiter opens a large door."),
        new DialogueLine("", "Inside sit three people."),
        new DialogueLine("", "The CEO and two panel members."),
        new DialogueLine("", "Yeonhee stood alone in the center of the room while the CEO and the panel members watched from the other side of the table."),
        new DialogueLine("", "For some reason it reminded her of the painting from class earlier."),
        new DialogueLine("", "Yeonhee bows until her head touches her knees."),
        new DialogueLine("Yeonhee", "Hi! I’m Yeonhee and I can sing and dance and-"),
        new DialogueLine("", "The CEO suddenly laughs."),
        new DialogueLine("", "Yeonhee stops talking."),
        new DialogueLine("Yeonhee", "I can’t tell if that was a good sign or a bad one."),
        new DialogueLine("Panel Member 2", "Don’t worry, we already know who you are."),
        new DialogueLine("", "A contract across the table towards me."),
        new DialogueLine("Panel Member 2", "He’s looking for people who are willing to dedicate themselves, not fans chasing fantasies."),
        new DialogueLine("", "I straighten my posture."),
        new DialogueLine("Yeonhee", "I’m in the top ten of my entire grade. I’m serious about anything I do."),
        new DialogueLine("", "I bow again."),
        new DialogueLine("Yeonhee", "Please take me in."),
        new DialogueLine("", "The CEO smiles."),
        new DialogueLine("CEO", "You're in."),
        new DialogueLine("Yeonhee", "What? Just like that? I didn’t even audition."),
        new DialogueLine("CEO", "That was the audition."),
        new DialogueLine("", "The contract sits in front of me."),
        new DialogueLine("", "For a moment, I hesitate."),
        new DialogueLine("", "I should probably read it."),
        new DialogueLine("", "Something in the back of my mind tells me I should…"),
        new DialogueLine("", "But I don't."),
        new DialogueLine("", "I signed it without a second thought."),
        new DialogueLine("", "The CEO's smile widens."),
        new DialogueLine("", "I stand up and bow, barely able to contain my excitement."),
        new DialogueLine("", "My dream is finally starting."),
        new DialogueLine("", "As I walk out of the room, I hear a quiet voice behind me"),
        new DialogueLine("", "“Another one signed.”"),
        new DialogueLine("", "I pause for a second."),
        new DialogueLine("", "…but I shake it off and keep walking."),
        new DialogueLine("", "All I can think about is my debut.")
        };

        dialogueManager.dialogueLines = dialogueLines;
        dialogueManager.index = 0;
        dialogueManager.ShowCurrentLine();
    }
}